import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  page: {
    fontFamily: "ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial",
    padding: 20,
    maxWidth: 1000,
    margin: "0 auto",
    color: "#111",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
    gap: 16,
    paddingBottom: 12,
    borderBottom: "1px solid #e5e7eb",
  },
  deckTitle: { fontSize: 28, fontWeight: 800, letterSpacing: -0.3 },
  deckMeta: { fontSize: 14, opacity: 0.7, marginTop: 2 },
  statsRow: { display: "flex", gap: 10 },
  stat: {
    border: "1px solid #e5e7eb",
    borderRadius: 12,
    padding: "10px 12px",
    minWidth: 88,
    textAlign: "center",
  },
  statValue: { fontSize: 18, fontWeight: 800 },
  statLabel: { fontSize: 12, opacity: 0.7 },

  tabs: { display: "flex", gap: 8, marginTop: 14 },
  tab: {
    border: "1px solid #e5e7eb",
    borderRadius: 999,
    padding: "8px 12px",
    background: "white",
    cursor: "pointer",
    fontWeight: 600,
  },
  tabActive: {
    borderColor: "#111",
  },

  main: { marginTop: 16 },
  section: { display: "flex", flexDirection: "column", gap: 12 },
  sectionHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 12 },
  h2: { fontSize: 18, fontWeight: 800 },
  h3: { fontSize: 14, fontWeight: 800, marginBottom: 8 },
  muted: { fontSize: 12, opacity: 0.7 },

  search: {
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: "8px 10px",
    minWidth: 240,
  },

  cardGrid: { display: "grid", gridTemplateColumns: "1fr", gap: 10 },
  cardRow: {
    border: "1px solid #e5e7eb",
    borderRadius: 14,
    padding: 12,
    background: "#fff",
  },
  cardFront: { fontSize: 14, fontWeight: 800, marginBottom: 4 },
  cardBack: { fontSize: 13, opacity: 0.85, whiteSpace: "pre-wrap" },
  cardActions: { display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 8 },
  checkbox: { fontSize: 12, display: "flex", gap: 6, alignItems: "center" },

  reviewBox: {
    border: "1px solid #e5e7eb",
    borderRadius: 16,
    padding: 16,
    background: "#fff",
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  reviewPrompt: { fontSize: 20, fontWeight: 900 },
  reviewAnswer: {
    borderTop: "1px dashed #e5e7eb",
    paddingTop: 12,
    fontSize: 14,
    whiteSpace: "pre-wrap",
  },
  ratingRow: { display: "flex", gap: 8, flexWrap: "wrap" },
  reviewFooter: { display: "flex", justifyContent: "space-between", alignItems: "center" },

  addGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  panel: { border: "1px solid #e5e7eb", borderRadius: 14, padding: 12, background: "#fff" },
  label: { fontSize: 12, fontWeight: 700, opacity: 0.8, display: "block", marginTop: 8 },
  textarea: {
    width: "100%",
    minHeight: 72,
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: 10,
    resize: "vertical",
    marginTop: 6,
    fontFamily: "inherit",
  },

  btn: {
    border: "1px solid #e5e7eb",
    borderRadius: 10,
    padding: "8px 10px",
    background: "white",
    cursor: "pointer",
    fontWeight: 700,
  },
  primaryBtn: {
    border: "1px solid #111",
    borderRadius: 10,
    padding: "10px 12px",
    background: "#111",
    color: "white",
    cursor: "pointer",
    fontWeight: 800,
  },
  dangerBtn: {
    border: "1px solid #ef4444",
    borderRadius: 10,
    padding: "8px 10px",
    background: "white",
    color: "#ef4444",
    cursor: "pointer",
    fontWeight: 800,
  },
  linkBtn: {
    border: "none",
    background: "transparent",
    padding: 0,
    cursor: "pointer",
    fontWeight: 800,
    textDecoration: "underline",
  },

  empty: {
    border: "1px dashed #e5e7eb",
    borderRadius: 14,
    padding: 16,
    background: "#fafafa",
    fontWeight: 700,
  },
  tip: { fontSize: 12, opacity: 0.7 },
};
